### ISSUE TITLE
Misc Quick Suggestions

### ISSUE THREAD

**Issue by JesseWebDotCom** [se1exin/Plex-Library-Cleaner#10]
A few misc suggestions that are likely quick to implement:

- Display the plex server name
- Maybe even make the name above link to the plex server’s web app (or add a little link arrow/icon next to the name)
- Keep a lifetime running total of space saved (either per server and or per library)
- Thumbnails for each movies would spice up the plain table view (might slow down the ui unacceptably, unknown)
- Maybe even link the movie names to the movie’s page in the plex server’s web app (or add a little link arrow/icon next to the name)

**Comment by se1exin** [comment]
I really like all these suggestions (and thanks for your interest in the project!). The only one that stands out as non-trivial to do is `Keep a lifetime running total of space saved`. The rest are simple UI changes which I will address soon in a new update, but tracking space saved will require a few technical decisions before proceeding. For that reason I have created a new issue #11 where we can continue the progress on that item.

**Comment by Alanoll** [comment]
Another couple of possible quick changes. I can create a new issue for them if you'd prefer instead.

* Deselect All - Unchecks all checked files. Maybe it's the user's first time running and they want to process one at a time.
* Select Non-Best - The inverse of the above. It rechecks everything (this is current functionality loading the page)
* Delete Selected Items - Have a delete button per movie. I may have multiple editions of multiple movies (LOTR / Underworld/ Blade/ etc), so I'd have to uncheck them each time I want to delete dupes. Per movies could allow iterative review and process.

**Comment by se1exin** [comment]
So I finally got some spare time to address all these. Please see the PR #35 for more details.

Also just a note, Dockerhub has stopped the automated builds, so I will need to setup a new build pipeline before you can access the new features. You can always clone and docker build it in the meantime 😄
