### ISSUE TITLE
SSL verification failed

### ISSUE THREAD

**Issue by booksarestillbetter** [se1exin/Plex-Library-Cleaner#2]
i attempted to set this up, but my server requires a secure connection, it appears that your code doesn't ignore ssl (in this case using the private returns a plex.direct ssl cert)

```
import requests 
session = requests.Session()
session.verify = False
pms = PlexServer(url, token, session=session)
```

**Comment by se1exin** [comment]
Thanks for the bug report, is your server using a self signed SSL cert (e.g. not issued from a known authority)?

I'd prefer not to hard code the bypass of certificate verification, would a container variable be suffice in this scenario? E.g. `docker run ... -e BYPASS_SSL_VERIFICATION=1 ...`?

**Comment by booksarestillbetter** [comment]
its using the standard plex.direct cert supplied by plex.tv. as for the bypassing verification i would prefer you didn't hard code it :) and ENV variable is fine.

**Comment by se1exin** [comment]
@booksarestillbetter the option `BYPASS_SSL_VERIFY` has been added. Add the following environment variable when running the container to activate it:

```
-e BYPASS_SSL_VERIFY=1
```
