### ISSUE TITLE
Is this for movies only?

### ISSUE THREAD

**Issue by okbrown** [se1exin/Plex-Library-Cleaner#34]
Is this for movies only?

**Comment by se1exin** [comment]
At the moment, yes. There are plans to add TV shows - and PRs are more than welcome!

**Comment by se1exin** [comment]
Issue created to track the progress of TV show implementation. Please continue the conversation there.

**Comment by okbrown** [comment]
Thanks for getting back, if I get some free time I be more than happy to raise a PR.
