### ISSUE TITLE
how does this pick dupes

### ISSUE THREAD

**Issue by pazport** [se1exin/Plex-Library-Cleaner#7]
i find this brilliant. but the only problem i have. that it is only picking 3 movies as dupes. when i a lot more then 3 dupes lol.

also wondering how does this pick up dupes etc. i have had this running for more then 4 hours. and it won't pick any more then 3 movies as dupes.

**Comment by mondychan** [comment]
yea, it also somehow selects which library to scan, i believe it selects library called "Movies", but thats just guess, my other movie libraries called different than "Movies" arent scanned it seems

**Comment by se1exin** [comment]
@pazport It 'finds' dupes by just asking your plex server for all Movie entries and then checks if there is more than one media file associated with that entry. If your plex is seeing each movie file as a separate Movie entry (e.g. it has matched different imdb/movie db titles) to each movie file, then this won't detect them as dupes. Admittedly the dupe finding isn't very sophisticated, but I found it good enough for my purposes. PRs for increased functionality are more than welcome though 😄 

@mondychan That is correct - it's currently hard coded to a library named `"Movies"`. I didn't put any effort into customising it as I thought I would wait until someone made noise that they actually used plex this way - which you now have, so I'll have a look at customising it when I get some spare time 😄 . Again, PRs are always welcome!

**Comment by pazport** [comment]
it's just i keep getting this ``Failed to load movies!

Please check your Plex settings and try again.``

maybe because my dupe library is really big i mean like 1k dupes lol. but i have tried 3 different tokens.
at 1st it only picked up 3 movies as dupes. then since i deleted those. it won't pickup any more. but in plex it says i have just over 1k dupes.

**Comment by se1exin** [comment]
@mondychan The docker container has been updated to allow custom library names using the `LIBRARY_NAMES` environment var. The readme has also been updated with details on how to do use custom library names.

@pazport I've updated the UI to show the error message from the backend when available rather than the generic 'Please check your Plex settings and try again` message. If possible can you update and let me know what the real error message is?

**Comment by pazport** [comment]
> 
> 
> @mondychan The docker container has been updated to allow custom library names using the `LIBRARY_NAMES` environment var. The readme has also been updated with details on how to do use custom library names.
> 
> @pazport I've updated the UI to show the error message from the backend when available rather than the generic `Please check your Plex settings and try again` message. If possible can you update and let me know what the real error message is?

yes i will, i will give it a shot tomorrow afternoone and let you know asap. and thanks for the update 👍

**Comment by mondychan** [comment]
fantastic job, works like a charm, thx for your time!
just a side question, seems not to support TV shows libraries yet?

**Comment by se1exin** [comment]
@mondychan great to hear the update is working well :smile:

In regards to TV libraries, unfortunately no not yet. Plex treats Movies and TV a bit differently under-the-hood - which I've only had time so far to address Movies as that was the bigger fish to fry (so to speak). TV is on my radar and hopefully I can get around to it soon..
